// import files
const express = require('express')

// import router
const postRouter = require('./routers/koder')

// import files generated by user
const app = express()
const port = 8080

// applying jsons
app.use(express.json())
app.use('/', postRouter)

// exporting files
module.exports = {
  server: app,
  port
}
